services:
  lightdiffusion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      # Mount output directory to persist generated images
      - ./output:/app/output
      # Mount checkpoints directory for model files
      - ./include/checkpoints:/app/include/checkpoints
      # Mount other model directories
      - ./include/loras:/app/include/loras
      - ./include/embeddings:/app/include/embeddings
      - ./include/ESRGAN:/app/include/ESRGAN
      - ./include/yolos:/app/include/yolos
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
    stdin_open: true
    tty: true
