services:
  lightdiffusion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      # Mount output directory to persist generated images
      - ./output:/app/_internal/output
      # Mount checkpoints directory for model files
      - ./checkpoints:/app/_internal/checkpoints
      # Mount other model directories
      - ./loras:/app/_internal/loras
      - ./embeddings:/app/_internal/embeddings
      - ./ESRGAN:/app/_internal/ESRGAN
      - ./yolos:/app/_internal/yolos
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
